[package]
name = "vaf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
dyn-clone = "1.0.17"
paste = "1.0.15"
thiserror = "1.0.61"
